services:
  nest-app:
    build: .
    image: nest-app
    env_file: .env
    ports:
      - '3001:3001'
    depends_on:
      - database
    volumes:
      - .:/src
      - server-volume:/server/node_modules
    networks:
      - node-network

  database:
    image: database:1.0.0
    container_name: 'mongo-db'
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - '27017:27017'
    volumes:
      - database-volume:/data/db

volumes:
  server-volume:
    name: "server-volume"
  database-volume:
    name: "database-volume"

networks:
  node-network:
    driver: bridge

